Academics page
utmmcss/mcss-website-cms pull request #12
Opened 2022-03-08 21:55 UTC by nigow

### Ticket
[Ticket Link](Link)

### What is changed / added
- short description of the PR

### Screenshots
- if applicable

2022-03-09 01:24 UTC, TheFatPanda97 requested changes
noice, just some small changes (keep in mind you can edit the field settings in the GUI, no need to edit the code 😃)

2022-03-09 01:24 UTC, TheFatPanda97 commented on src/api/academic/content-types/academic/schema.json
> +      "allowedTypes": [
let's only allow images here
<img width="873" alt="Screen Shot 2022-03-08 at 8 22 21 PM" src="https://user-images.githubusercontent.com/36747253/157353925-b08ef1b3-404f-413d-b94c-7240842f6345.png">

2022-03-09 01:24 UTC, TheFatPanda97 commented on src/api/academic/content-types/academic/schema.json
> +    },
let's make this required and default to false
<img width="864" alt="Screen Shot 2022-03-08 at 8 23 15 PM" src="https://user-images.githubusercontent.com/36747253/157354020-25a5b90f-08ee-4255-8dd9-25d29061b814.png">

2022-03-09 15:14 UTC, nigow commented on src/api/academic/content-types/academic/schema.json
> +    },
good catch, changed both fields

2022-03-14 21:42 UTC, TheFatPanda97 approved these changes

2022-03-16 00:07 UTC, merged